### ISSUE TITLE
Command `sstat` could not be found

### ISSUE THREAD

**Issue by dlazesz** [sassbalint/double-cube-jump-and-stay-multilingual#2]
In commit 5dde1d77998153f7b22fdb644f50dab10ee8b284 `sstat` command should be replaced in [convert2json.sh#L20](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/convert2json.sh#L20) and [process_conll.sh#L21](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/process_conll.sh#L21) to `sort | uniq -c | sort -nr` else `make` will fail!

**Comment by sassbalint** [comment]
Thanks! Done. 9f1d29e
