### ISSUE TITLE
LANG environment variable is reserved by the operating system

### ISSUE THREAD

**Issue by dlazesz** [sassbalint/double-cube-jump-and-stay-multilingual#3]
In commit 5dde1d77998153f7b22fdb644f50dab10ee8b284 `LANG` variable in [process_conll.sh#L10](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/process_conll.sh#L10), [process_conll.sh#L20](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/process_conll.sh#L20), [process_conll.sh#L10](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/process_conll.sh#L10) and in multiple lines of [Makefile](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/Makefile#L2) should be replaced with something else. `LANG` is related to locales. Changing it results using different locales for the rest of the script. These locales may not present and result in an error. If this is intended please make it explicit. IMO changing the locale is not necessary.

**Comment by sassbalint** [comment]
Thanks! Done. 9f1d29e
