### ISSUE TITLE
impl.py differs in one line from the original repo. Should be promoted to a CLI parameter!

### ISSUE THREAD

**Issue by dlazesz** [sassbalint/double-cube-jump-and-stay-multilingual#5]
In commit [5dde1d7](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/commit/5dde1d77998153f7b22fdb644f50dab10ee8b284) the file [impl.py](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/impl.py) differs in tow lines from the [original file](https://github.com/sassbalint/double-cube-jump-and-stay/blob/master/impl.py)

The [original file line 102-104](https://github.com/sassbalint/double-cube-jump-and-stay/blob/master/impl.py#L102) show:

```
  # = if there is no NOM slot => add "NOM":None
  if "NOM" not in d:
    d["NOM"] = None
```

But [in this repo same lines](https://github.com/sassbalint/double-cube-jump-and-stay-multilingual/blob/master/impl.py#L102) show: 

```
  # = if there is no NOM slot => add "NOM":None
  if "nsubj" not in d:
    d["nsubj"] = None
```
This should be set from the CLI to be able to use the same code in both repos.

**Comment by sassbalint** [comment]
Solved in 0fc43d3.
